name: vehiclesMicroservice
on:
  release:
    types: [published]
    branches:
      - main
  workflow_dispatch:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 18.18.0
      - name: Install dependencies
        working-directory: ./
        run: npm install
      - name: Run Tests
        working-directory: ./
        run: npm test
             
  Build:
    runs-on: ubuntu-latest
    needs: Test
    steps:
    - name: Build
      uses: actions/checkout@v3
    - name: Set Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - name: npm install
      run: npm install
        
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Login on Docker
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build Image
        working-directory: ./
        run: docker build -t allcarsinone/vehicles_service:${{ github.sha }} -t allcarsinone/vehicles_service:latest .
      - name: Push to Docker Step 1
        run: docker push allcarsinone/vehicles_service:${{ github.sha }}
      - name: Push to Docker Step 2
        run: docker push allcarsinone/vehicles_service:latest
